name: Checkout
on: push
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - uses: actions/checkout@master
        with:
          repository: wnynya/Wanyne-API-config
          token: ${{ secrets.CONFIG_TOKEN }}
          path: './config'

      - run: npm cache verify

      - run: npm install

      - run: ./start.sh
